#databases in postgresql

common: &common
  adapter: postgresql
  username: rnaud
  encoding: utf8
  password: melchi # from psql setup, see Postgresql

development:
  <<: *common
  database: getbeer_dev

test:
  <<: *common
  database: getbeer_test

production:
  <<: *common
  database: getbeer