defaults: &defaults
  app_name: "Getbeer"

development:
  app_id: TOLGVLWXY20NEYXLU1AZVZGEHLUXY3FIF1YEJYHS515YZENA
  app_secret: XAKFC3QZ2HRI4UQ24FZP1WW5ALTIVSXSCJFHQ3NQQVOB220S
  <<: *defaults

test:
  <<: *defaults

production:
  app_id: BVH5AEHDIHEQEIB5AEJEHUTEKAOPIBIBMHRDLEUKR31BHEIT
  app_secret: L01J0F4N3KMFLV4HGXSKDAIMEDOGQIMMSUAT3OLL5KIKBLIT
  <<: *defaults